[phases.setup]
aptPkgs = ["nodejs", "npm", "nginx"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build", "cp -r frontend/dist /tmp/frontend-dist", "mkdir -p /etc/nginx/conf.d", "cp nginx.conf /etc/nginx/conf.d/default.conf", "chmod +x start.sh"]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
PORT = "3001"