[phases.setup]
aptPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend/dist/src/index.js"

[variables]
NODE_ENV = "production"
PORT = "3001"